# Generated by Django 5.2.15 on 2026-06-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.location', verbose_name='Lokasi'),
        ),
    ]
