# Generated by Django 5.2.15 on 2026-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.division', verbose_name='Divisi'),
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.location', verbose_name='Lokasi'),
        ),
    ]
