# Generated by Django 5.2.15 on 2026-06-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Kontak')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Kode (SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('unit', models.CharField(choices=[('pcs', 'Pcs'), ('box', 'Box'), ('kg', 'Kg'), ('liter', 'Liter'), ('pack', 'Pack')], default='pcs', max_length=10, verbose_name='Satuan')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='Stok Minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='warehouse.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['name'],
            },
        ),
    ]
