# Generated by Django 5.2.15 on 2026-06-22 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar'), ('adjustment', 'Penyesuaian')], max_length=12, verbose_name='Jenis')),
                ('quantity', models.PositiveIntegerField(help_text='Untuk Masuk/Keluar: jumlah yang bergerak. Untuk Penyesuaian: jumlah stok yang sebenarnya (hasil hitung fisik).', verbose_name='Jumlah')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Catatan')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='No. Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.item', verbose_name='Barang')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.supplier', verbose_name='Supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Pencatat')),
            ],
            options={
                'verbose_name': 'Transaksi Stok',
                'verbose_name_plural': 'Transaksi Stok',
                'ordering': ['-created_at'],
            },
        ),
    ]
