# Generated by Django 5.2.15 on 2026-06-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location_user_location'),
        ('warehouse', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.location', verbose_name='Lokasi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='Kode (SKU)'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('location', 'sku'), name='uniq_item_sku_per_location'),
        ),
    ]
