# Generated by Django 5.2.15 on 2026-06-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_item_location_alter_item_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hilangkan centang untuk menonaktifkan barang (disembunyikan dari daftar, tanpa menghapus data & riwayatnya).', verbose_name='Aktif'),
        ),
    ]
