# Generated by Django 5.2.15 on 2026-06-26 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_user_division_remove_user_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama')),
            ],
            options={
                'verbose_name': 'Kategori Produksi',
                'verbose_name_plural': 'Kategori Produksi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Kontak')),
            ],
            options={
                'verbose_name': 'Supplier Produksi',
                'verbose_name_plural': 'Supplier Produksi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='Kode (SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('unit', models.CharField(choices=[('pcs', 'Pcs'), ('box', 'Box'), ('kg', 'Kg'), ('liter', 'Liter'), ('pack', 'Pack')], default='pcs', max_length=10, verbose_name='Satuan')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='Stok Minimum')),
                ('is_active', models.BooleanField(default=True, help_text='Hilangkan centang untuk menonaktifkan barang (disembunyikan dari daftar, tanpa menghapus data & riwayatnya).', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='production.productioncategory', verbose_name='Kategori')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_items', to='core.location', verbose_name='Lokasi')),
            ],
            options={
                'verbose_name': 'Barang Produksi',
                'verbose_name_plural': 'Barang Produksi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar'), ('adjustment', 'Penyesuaian')], max_length=12, verbose_name='Jenis')),
                ('quantity', models.PositiveIntegerField(help_text='Untuk Masuk/Keluar: jumlah yang bergerak. Untuk Penyesuaian: jumlah stok yang sebenarnya (hasil hitung fisik).', verbose_name='Jumlah')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Catatan')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='No. Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='production.productionitem', verbose_name='Barang')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_movements', to=settings.AUTH_USER_MODEL, verbose_name='Pencatat')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='production.productionsupplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Transaksi Produksi',
                'verbose_name_plural': 'Transaksi Produksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionitem',
            constraint=models.UniqueConstraint(fields=('location', 'sku'), name='uniq_production_item_sku_per_location'),
        ),
    ]
