# Generated by Django 5.2.15 on 2026-06-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesin_kode', models.CharField(db_index=True, max_length=30, verbose_name='Mesin')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('shift', models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=1, verbose_name='Shift')),
                ('jam_mulai', models.TimeField(verbose_name='Jam mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam selesai')),
                ('nomor_produksi', models.CharField(blank=True, max_length=100, verbose_name='Nomor produksi')),
                ('input', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Input')),
                ('output', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Output')),
                ('scrap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Scrap')),
                ('defect_ng', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Defect / NG')),
                ('next_proses', models.CharField(blank=True, max_length=150, verbose_name='Next process')),
                ('petugas', models.CharField(help_text='Operator yang memantau mesin.', max_length=150, verbose_name='Petugas')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Detail mesin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu input')),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catatan_produksi', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat oleh')),
            ],
            options={
                'verbose_name': 'Catatan Produksi',
                'verbose_name_plural': 'Catatan Produksi',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
